AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the IO Intensive JDK 17 Snapstart
  API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://io-jdk17-snapstart-artifacts-49b954a54ce7148a/201d99bc369e466365054e720b6a9940
      Handler: example.Handler
      Runtime: java17
      Description: Java 17 IO Intensive function for snapstart
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
