AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Empty JDK17 Provisioned Concurrency
  API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://blank-jdk17-provisioned-concurrency-artifacts-db79c99d79f9efea/2ef1abebfcb64f87477c8b19c720d600
      Handler: example.Handler::handleRequest
      Runtime: java17
      Description: Java 17 empty function for provisioned concurrency
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-jdk17-provisioned-concurrency-lib
      Description: Dependencies for the blank-jdk17-provisioned-concurrency sample
        app.
      ContentUri: s3://blank-jdk17-provisioned-concurrency-artifacts-db79c99d79f9efea/4f54b405e7efa63114981bba67f10a57
      CompatibleRuntimes:
      - java17
