AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Empty JDK17 Provisioned Concurrency API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/blank-jdk17-provisioned-concurrency.zip
      Handler: example.Handler::handleRequest
      Runtime: java17
      Description: Java 17 empty function for provisioned concurrency
      MemorySize: 2048
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-jdk17-provisioned-concurrency-lib
      Description: Dependencies for the blank-jdk17-provisioned-concurrency sample app.
      ContentUri: build/blank-jdk17-provisioned-concurrency-lib.zip
      CompatibleRuntimes:
        - java17