AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Empty JDK17 Snapstart API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://blank-jdk17-snapstart-artifacts-a2003a0d6bbe7dfa/6f188a7e77b2eac172f25a6a38600e1d
      Handler: example.Handler::handleRequest
      Runtime: java17
      Description: Java 17 empty function for snapstart
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-jdk17-snapstart-lib
      Description: Dependencies for the blank-jdk17-snapstart sample app.
      ContentUri: s3://blank-jdk17-snapstart-artifacts-a2003a0d6bbe7dfa/5930c7af1142326012f9d7dd1aacf2c1
      CompatibleRuntimes:
      - java17
