AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the IO Intensive JDK 11 Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://io-jdk11-lambda-artifacts-aaaec440e875e547/e9fed42720e970bb8b2734916cca286e
      Handler: example.Handler
      Runtime: java11
      Description: Java 11 IO Intensive function for lambda
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
