AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the CPU Intensive JDK 11 SnapStart
  API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cpu-jdk11-snapstart-artifacts-b1a19c0209f4ea9c/752d0cc8d1abb5ec80bff4e58c2e224e
      Handler: example.Handler::handleRequest
      Runtime: java11
      Description: Java 11 CPU Intensive function for snapstart
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: cpu-jdk11-snapstart-lib
      Description: Dependencies for the cpu-jdk11-snapstart sample app.
      ContentUri: s3://cpu-jdk11-snapstart-artifacts-b1a19c0209f4ea9c/7216c42e5faf299f1de3b1f9ec9a82d3
      CompatibleRuntimes:
      - java11
